version: '3.8'
name: smart-home-dashboard

services:
  web:
    build:
      context: ../../src/web
      dockerfile: ../infrastructure/docker/Dockerfile.web
      args:
        NODE_ENV: production
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - smart-home-dashboard
    volumes:
      - node_modules:/app/node_modules
    configs:
      - source: nginx_conf
        target: /etc/nginx/conf.d/default.conf
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      - NODE_ENV=production
      - TZ=UTC

  backend:
    build:
      context: ../../src/backend
      dockerfile: ../infrastructure/docker/Dockerfile.backend
      args:
        NODE_ENV: production
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - smart-home-dashboard
    volumes:
      - node_modules:/app/node_modules
    deploy:
      resources:
        limits:
          cpus: '1.00'
          memory: 1G
        reservations:
          cpus: '0.50'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  smart-home-dashboard:
    driver: bridge
    name: smart-home-dashboard
    driver_opts:
      com.docker.network.bridge.name: "smart-home-net"
    ipam:
      driver: default
      config:
        - subnet: 172.28.0.0/16

volumes:
  node_modules:
    driver: local

configs:
  nginx_conf:
    file: ./nginx.conf