apiVersion: v1
kind: ConfigMap
metadata:
  name: smart-home-dashboard-config
  namespace: default
  labels:
    app: smart-home-dashboard
    component: configuration
    environment: production
  annotations:
    config.version: "1.0.0"
    config.last-updated: "2024-01-01"
    config.description: "Smart Home Dashboard configuration for production environment"
    config.security.classification: "non-sensitive"
    config.update-strategy: "manual-with-rolling-deployment"
data:
  # Backend Configuration
  BACKEND_CONFIG: |
    {
      "NODE_ENV": "production",
      "PORT": "3000",
      "HOST": "0.0.0.0",
      "LOG_LEVEL": "info",
      "CORS_ORIGIN": "https://dashboard.example.com",
      "RATE_LIMIT_WINDOW": "15m",
      "RATE_LIMIT_MAX_REQUESTS": "100",
      "API_VERSION": "v1",
      "METRICS_ENABLED": "true",
      "REQUEST_TIMEOUT": "30s",
      "MAX_PAYLOAD_SIZE": "1mb",
      "COMPRESSION_ENABLED": "true",
      "TRUST_PROXY": "true",
      "HEALTH_CHECK_PATH": "/health",
      "API_DOCS_PATH": "/api-docs"
    }

  # Frontend Configuration
  FRONTEND_CONFIG: |
    {
      "VITE_APP_ENV": "production",
      "VITE_APP_API_URL": "https://api.dashboard.example.com",
      "VITE_APP_WS_URL": "wss://api.dashboard.example.com",
      "VITE_APP_LOG_LEVEL": "error",
      "VITE_APP_VERSION": "1.0.0",
      "VITE_APP_BUILD_TIME": "2024-01-01T00:00:00Z",
      "VITE_APP_TITLE": "Smart Home Dashboard",
      "VITE_APP_DESCRIPTION": "Visual smart home control interface",
      "VITE_APP_THEME": "system",
      "VITE_APP_DEFAULT_LANGUAGE": "en",
      "VITE_APP_SUPPORT_EMAIL": "support@dashboard.example.com",
      "VITE_APP_MAX_FLOOR_PLANS": "10",
      "VITE_APP_MAX_ENTITIES_PER_PLAN": "100",
      "VITE_APP_WEBSOCKET_RECONNECT_INTERVAL": "5000",
      "VITE_APP_WEBSOCKET_MAX_RETRIES": "5"
    }

  # Common Configuration
  COMMON_CONFIG: |
    {
      "APP_NAME": "smart-home-dashboard",
      "ENVIRONMENT": "production",
      "REGION": "default",
      "MONITORING_ENABLED": "true",
      "TELEMETRY_ENABLED": "true",
      "SUPPORT_CONTACT": "support@dashboard.example.com",
      "DOCUMENTATION_URL": "https://docs.dashboard.example.com",
      "BACKUP_ENABLED": "true",
      "METRICS_RETENTION_DAYS": "30"
    }

  # Deployment Configuration
  DEPLOYMENT_CONFIG: |
    {
      "VERSION": "1.0.0",
      "RELEASE_DATE": "2024-01-01",
      "MAINTAINER": "DevOps Team",
      "REPOSITORY": "https://github.com/org/smart-home-dashboard",
      "DEPLOYMENT_TYPE": "kubernetes",
      "CLUSTER_NAME": "production",
      "UPDATE_STRATEGY": "RollingUpdate",
      "ROLLBACK_ENABLED": "true"
    }