apiVersion: v1
kind: Secret
metadata:
  name: smart-home-dashboard-secrets
  namespace: default
  labels:
    app: smart-home-dashboard
    component: secrets
    managed-by: manual
    rotation-due: 90-days
  annotations:
    created-by: kubernetes-admin
    created-at: "2024-01-01T00:00:00Z"  # Example timestamp
    last-rotated: "2024-01-01T00:00:00Z"  # Example timestamp
    rotation-schedule: 90-days
    encryption: aes-256-gcm
    backup-policy: encrypted-only
    secret-version: v1
type: Opaque
data:
  # Backend Secrets
  JWT_SECRET: ${BASE64_JWT_SECRET}  # Replace with actual base64 encoded value
  DATABASE_URL: ${BASE64_DATABASE_URL}  # Replace with actual base64 encoded value
  HOME_ASSISTANT_TOKEN: ${BASE64_HOME_ASSISTANT_TOKEN}  # Replace with actual base64 encoded value
  ENCRYPTION_KEY: ${BASE64_ENCRYPTION_KEY}  # Replace with actual base64 encoded value
  SESSION_SECRET: ${BASE64_SESSION_SECRET}  # Replace with actual base64 encoded value
  WSS_CERT: ${BASE64_WSS_CERT}  # Replace with actual base64 encoded value
  WSS_KEY: ${BASE64_WSS_KEY}  # Replace with actual base64 encoded value
  REDIS_URL: ${BASE64_REDIS_URL}  # Replace with actual base64 encoded value
  API_KEYS: ${BASE64_API_KEYS}  # Replace with actual base64 encoded value
  BACKUP_ENCRYPTION_KEY: ${BASE64_BACKUP_ENCRYPTION_KEY}  # Replace with actual base64 encoded value

  # Frontend/Web Secrets
  VITE_APP_HOME_ASSISTANT_TOKEN: ${BASE64_VITE_APP_HOME_ASSISTANT_TOKEN}  # Replace with actual base64 encoded value
  VITE_APP_API_URL: ${BASE64_VITE_APP_API_URL}  # Replace with actual base64 encoded value
  VITE_APP_WSS_URL: ${BASE64_VITE_APP_WSS_URL}  # Replace with actual base64 encoded value
  VITE_APP_PUBLIC_KEY: ${BASE64_VITE_APP_PUBLIC_KEY}  # Replace with actual base64 encoded value